version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  hasura:
    image: hasura/graphql-engine:v2.0.0.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    working_dir: /hasura
    restart: always
    volumes:
      - ./hasura:/hasura
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura/migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura/metadata
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      VUE_APP_TEST: test
  ngrok:
    image: shkoliar/ngrok:latest
    command: sh -c "ngrok authtoken ${NGROK_AUTHTOKEN} && ./start.sh"
    ports:
      - 4551:4551
    environment:
      - DOMAIN=app
      - PORT=3000
      - BIND_TLS=true
    depends_on:
      - "app"
volumes:
  db_data:
